import { Handover, HandoverSection, HandoverItem } from './types';

const PRIORITY_CONFIG: Record<string, { color: string; bg: string; icon: string; border: string }> = {
  critical: { color: '#991b1b', bg: '#fef2f2', icon: '🔴', border: '#fca5a5' },
  high:     { color: '#92400e', bg: '#fffbeb', icon: '🟡', border: '#fcd34d' },
  medium:   { color: '#1e40af', bg: '#eff6ff', icon: '🔵', border: '#93c5fd' },
  low:      { color: '#166534', bg: '#f0fdf4', icon: '✅', border: '#86efac' },
  info:     { color: '#374151', bg: '#f9fafb', icon: 'ℹ️', border: '#d1d5db' },
};

function flagBadge(flag: string): string {
  const styles: Record<string, string> = {
    CONFLICT: 'background:#fef3c7;color:#92400e;border:1px solid #fcd34d',
    UNVERIFIED: 'background:#f3f4f6;color:#374151;border:1px solid #d1d5db',
    SECURITY: 'background:#fce7f3;color:#9d174d;border:1px solid #f9a8d4',
    GAP: 'background:#ede9fe;color:#5b21b6;border:1px solid #c4b5fd',
  };
  const style = styles[flag] ?? 'background:#f3f4f6;color:#374151;border:1px solid #d1d5db';
  return `<span style="font-size:11px;padding:2px 7px;border-radius:12px;font-weight:600;${style}">${flag}</span>`;
}

function renderItem(item: HandoverItem): string {
  const flags = (item.flags ?? []).map(flagBadge).join(' ');
  const roomGuest = [item.room ? `Room ${item.room}` : null, item.guest ? item.guest : null]
    .filter(Boolean)
    .join(' · ');

  return `
    <div style="padding:14px 16px;border-bottom:1px solid #f0f0f0;">
      <div style="display:flex;align-items:flex-start;gap:10px;justify-content:space-between;flex-wrap:wrap;">
        <div>
          <div style="font-weight:600;font-size:14px;color:#111827;margin-bottom:4px;">${item.summary}</div>
          ${roomGuest ? `<div style="font-size:12px;color:#6b7280;margin-bottom:6px;">${roomGuest}</div>` : ''}
          <div style="font-size:13px;color:#374151;line-height:1.5;margin-bottom:8px;">${item.detail}</div>
          <div style="font-size:11px;color:#9ca3af;background:#f9fafb;border-left:3px solid #e5e7eb;padding:6px 10px;border-radius:0 4px 4px 0;font-family:monospace;line-height:1.4;">${item.sourceQuote}</div>
        </div>
        ${flags ? `<div style="display:flex;gap:4px;flex-wrap:wrap;flex-shrink:0;">${flags}</div>` : ''}
      </div>
    </div>`;
}

function renderSection(section: HandoverSection): string {
  const cfg = PRIORITY_CONFIG[section.priority] ?? PRIORITY_CONFIG.info;
  const items = (section.items as HandoverItem[]).map(renderItem).join('');

  return `
  <div style="margin-bottom:20px;border-radius:8px;border:1px solid ${cfg.border};overflow:hidden;">
    <div style="background:${cfg.bg};padding:12px 16px;border-bottom:1px solid ${cfg.border};display:flex;align-items:center;gap:8px;">
      <span style="font-size:16px;">${cfg.icon}</span>
      <span style="font-weight:700;font-size:15px;color:${cfg.color};">${section.title}</span>
      <span style="margin-left:auto;font-size:12px;color:${cfg.color};background:${cfg.border};padding:2px 8px;border-radius:10px;">${section.items.length} item${section.items.length !== 1 ? 's' : ''}</span>
    </div>
    ${items}
  </div>`;
}

export function renderHTML(handover: Handover): string {
  const sections = handover.sections.map(renderSection).join('');
  const now = new Date(handover.generatedAt).toLocaleString('en-SG', {
    timeZone: 'Asia/Singapore',
    dateStyle: 'full',
    timeStyle: 'short',
  });

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8"/>
  <meta name="viewport" content="width=device-width,initial-scale=1"/>
  <title>Night Shift Handover — ${handover.hotelName} — ${handover.shiftDate}</title>
  <style>
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; background: #f3f4f6; min-height: 100vh; }
    .container { max-width: 820px; margin: 0 auto; padding: 24px 16px; }
    .header { background: #111827; color: white; border-radius: 10px; padding: 20px 24px; margin-bottom: 24px; }
    .header h1 { font-size: 20px; font-weight: 700; margin-bottom: 4px; }
    .header .meta { font-size: 13px; color: #9ca3af; display: flex; gap: 16px; flex-wrap: wrap; margin-top: 8px; }
    .header .meta span { display: flex; align-items: center; gap: 4px; }
    .footer { text-align: center; font-size: 11px; color: #9ca3af; margin-top: 24px; padding-bottom: 16px; }
  </style>
</head>
<body>
  <div class="container">
    <div class="header">
      <h1>Night Shift Handover</h1>
      <div style="font-size:16px;color:#e5e7eb;margin-top:4px;">${handover.hotelName}</div>
      <div class="meta">
        <span>📅 Morning of ${handover.shiftDate}</span>
        <span>🕐 Generated ${now}</span>
        <span>🏨 ${handover.hotelId}</span>
      </div>
    </div>
    ${sections}
    <div class="footer">Generated by Vouch Handover Service · Every statement grounded in source data · Flags indicate items needing human verification</div>
  </div>
</body>
</html>`;
}
